//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faktura()
        {
            this.PozycjaFaktury = new HashSet<PozycjaFaktury>();
        }
    
        public int IDFaktury { get; set; }
        public string Numer { get; set; }
        public Nullable<int> IDKontrahenta { get; set; }
        public Nullable<int> IDSposobuPlatnosci { get; set; }
        public Nullable<int> IDStatusuFaktury { get; set; }
        public Nullable<int> IDRodzajuKwoty { get; set; }
        public Nullable<System.DateTime> DataSprzedazy { get; set; }
        public Nullable<System.DateTime> DataWystawienia { get; set; }
        public Nullable<System.DateTime> TerminPlatnosci { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public Nullable<int> KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyDodal { get; set; }
        public Nullable<int> KtoZmodyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyZModyfikowal { get; set; }
        public Nullable<int> KtoUsunal { get; set; }
        public Nullable<System.DateTime> KiedyUsunal { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Kontrahent Kontrahent { get; set; }
        public virtual RodzajKwoty RodzajKwoty { get; set; }
        public virtual SposobPlatnosci SposobPlatnosci { get; set; }
        public virtual StatusFaktury StatusFaktury { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaFaktury> PozycjaFaktury { get; set; }
    }
}
