//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GabinetEntities4 : DbContext
    {
        public GabinetEntities4()
            : base("name=GabinetEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<EWizyta> EWizyta { get; set; }
        public virtual DbSet<Faktura> Faktura { get; set; }
        public virtual DbSet<JednostkaMiary> JednostkaMiary { get; set; }
        public virtual DbSet<Kontrahent> Kontrahent { get; set; }
        public virtual DbSet<Kraj> Kraj { get; set; }
        public virtual DbSet<OddziałNFZ> OddziałNFZ { get; set; }
        public virtual DbSet<Pacjent> Pacjent { get; set; }
        public virtual DbSet<PozycjaFaktury> PozycjaFaktury { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<RodzajKwoty> RodzajKwoty { get; set; }
        public virtual DbSet<RodzajWizyty> RodzajWizyty { get; set; }
        public virtual DbSet<Skierowanie> Skierowanie { get; set; }
        public virtual DbSet<SposobPlatnosci> SposobPlatnosci { get; set; }
        public virtual DbSet<StatusFaktury> StatusFaktury { get; set; }
        public virtual DbSet<StatusPacjenta> StatusPacjenta { get; set; }
        public virtual DbSet<TypWizyty> TypWizyty { get; set; }
        public virtual DbSet<Usluga> Usluga { get; set; }
        public virtual DbSet<UslugaKontrahent> UslugaKontrahent { get; set; }
        public virtual DbSet<Wizyta> Wizyta { get; set; }
        public virtual DbSet<Wojewodztwo> Wojewodztwo { get; set; }
    }
}
