//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozycjaFaktury
    {
        public int IDPozycjiFaktury { get; set; }
        public Nullable<int> IDFaktury { get; set; }
        public Nullable<int> IDUslugi { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public Nullable<decimal> Ilosc { get; set; }
        public Nullable<int> IDJednostkiMiary { get; set; }
        public Nullable<decimal> Rabat { get; set; }
        public Nullable<decimal> Wartosc { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public Nullable<int> KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyDodal { get; set; }
        public Nullable<int> KtoZmodyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyZModyfikowal { get; set; }
        public Nullable<int> KtoUsunal { get; set; }
        public Nullable<System.DateTime> KiedyUsunal { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Faktura Faktura { get; set; }
        public virtual JednostkaMiary JednostkaMiary { get; set; }
        public virtual UslugaKontrahent UslugaKontrahent { get; set; }
    }
}
