//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        public int IDPracownika { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Stanowisko { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public Nullable<int> KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyDodal { get; set; }
        public Nullable<int> KtoZmodyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyZModyfikowal { get; set; }
        public Nullable<int> KtoUsunal { get; set; }
        public Nullable<System.DateTime> KiedyUsunal { get; set; }
        public string Uwagi { get; set; }
    }
}
