//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyta
    {
        public int IDWizyty { get; set; }
        public Nullable<int> IDPacjenta { get; set; }
        public Nullable<int> IDRodzajuWizyty { get; set; }
        public Nullable<int> IDEWizyty { get; set; }
        public Nullable<int> IDTypuWizyty { get; set; }
        public Nullable<int> IDSkierowania { get; set; }
        public Nullable<int> IDUslugi { get; set; }
        public Nullable<System.DateTime> DataWizyty { get; set; }
        public string GodzinaWizyty { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public Nullable<int> KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyDodal { get; set; }
        public Nullable<int> KtoZmodyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyZModyfikowal { get; set; }
        public Nullable<int> KtoUsunal { get; set; }
        public Nullable<System.DateTime> KiedyUsunal { get; set; }
        public string Uwagi { get; set; }
    
        public virtual EWizyta EWizyta { get; set; }
        public virtual Pacjent Pacjent { get; set; }
        public virtual RodzajWizyty RodzajWizyty { get; set; }
        public virtual Skierowanie Skierowanie { get; set; }
        public virtual TypWizyty TypWizyty { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
